name: Build zmk firmware
on:
  push:
    branches:
      - master
      - "feature/**"
    paths:
      - "config/**"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
